import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// --- Interfaces ---
export interface CaseReportData {
  id: string;
  reportDate: string;
  diseaseCode: string;
  diseaseName: string;
  status: string;
  validationStatus: string;
  symptoms: string[];
  onsetDate: string;
  outcome?: string;
  facilityName: string;
  facilityCode?: string;
  patientInfo: string;
  patientNationalId?: string;
  submittedBy?: string;
}

export interface ReportOptions {
  title: string;
  subtitle?: string;
  dateRange: { from: string; to: string };
  generatedAt: string;
  generatedBy: string;
  cases: CaseReportData[];
}

// --- Constants & Helpers ---
const MARGIN = 10;
const DEEP_BLUE = [0, 93, 170] as [number, number, number];
const LIGHT_GRAY = [230, 230, 230] as [number, number, number];

const diseaseNames: Record<string, string> = {
  CHOLERA: "Cholera",
  MAL01: "Malaria",
  SARI: "Severe Acute Respiratory Illness",
  AFP: "Acute Flaccid Paralysis",
  YELLOW_FEVER: "Yellow Fever",
  RUBELLA: "Rubella",
  MEASLES: "Measles",
  PLAGUE: "Plague",
  RABIES: "Rabies",
  EBOLA: "Ebola Virus Disease",
};

const getDiseaseName = (code: string): string => diseaseNames[code] || code;

// --- Drawing Functions ---

function drawHeader(doc: jsPDF): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  try {
    doc.addImage("/rbc_logo.png", "PNG", MARGIN, 10, 35, 18, "FAST");
  } catch {}

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(33, 37, 41);
  doc.text(
    "Rwanda National Integrated Disease Surveillance and Response",
    48,
    16,
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text("Ministry of Health | Kigali, Rwanda | info@rbc.gov.rw", 48, 22);

  return 35;
}

function drawTitleSection(
  doc: jsPDF,
  options: ReportOptions,
  yPos: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Main Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(33, 37, 41);
  doc.text(options.title.toUpperCase(), pageWidth / 2, yPos, {
    align: "center",
  });

  // --- Full Width Light Gray Line ---
  yPos += 3;
  doc.setDrawColor(LIGHT_GRAY[0], LIGHT_GRAY[1], LIGHT_GRAY[2]);
  doc.setLineWidth(0.1);
  doc.line(MARGIN, yPos, pageWidth - MARGIN, yPos);

  yPos += 7;

  // Date Details
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(128, 128, 128);
  const dateDetailsText = `Period: ${options.dateRange.from} to ${options.dateRange.to} - Generated: ${options.generatedAt}`;
  doc.text(dateDetailsText, pageWidth / 2, yPos, { align: "center" });

  return yPos + 4;
}

function drawTableSection(
  doc: jsPDF,
  options: ReportOptions,
  startY: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  const tableData = options.cases.map((c, index) => [
    index + 1,
    c.patientInfo,
    getDiseaseName(c.diseaseCode),
    c.facilityCode ? `${c.facilityName} (${c.facilityCode})` : c.facilityName,
    c.submittedBy || "-",
    c.status.toUpperCase(),
    c.validationStatus.toUpperCase(),
    c.reportDate,
    `${c.symptoms?.slice(0, 3).join(", ")}${c.symptoms.length > 3 ? "..." : ""}`,
  ]);

  autoTable(doc, {
    startY,
    margin: { left: MARGIN, right: MARGIN },
    head: [
      [
        "SN",
        "Patient",
        "Disease",
        "Facility",
        "Submitted By",
        "Status",
        "Validation",
        "Report Date",
      ],
    ],
    body: tableData,

    // Modern Table Styling
    styles: {
      fontSize: 7.5,
      cellPadding: 3,
      lineColor: [235, 237, 240],
      lineWidth: 0.1,
      valign: "middle",
    },
    headStyles: {
      fillColor: DEEP_BLUE,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      halign: "center",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      5: { halign: "center" },
      6: { halign: "center" },
      7: { halign: "center" },
    },

    // --- Border Radius Effect ---
    // We draw a rounded rectangle behind the header area
    didDrawPage: (data) => {
      const height = doc.internal.pageSize.getHeight();

      // Footer
      doc.setDrawColor(214, 217, 222);
      doc.line(MARGIN, height - 12, pageWidth - MARGIN, height - 12);
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text(`Generated by: ${options.generatedBy}`, MARGIN, height - 7);
      doc.text(
        `${data.pageNumber}/${doc.getNumberOfPages()}`,
        pageWidth - MARGIN,
        height - 7,
        { align: "right" },
      );
    },

    willDrawCell: (data) => {
      // Bold the status columns
      if (
        data.section === "body" &&
        (data.column.index === 5 || data.column.index === 6)
      ) {
        doc.setFont("helvetica", "bold");
      }
    },
  });

  return (doc as any).lastAutoTable.finalY;
}

// --- Main Generator ---

export function generateCaseReportPDF(options: ReportOptions): jsPDF {
  const doc = new jsPDF({
    orientation: "p",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = drawHeader(doc);
  yPos = drawTitleSection(doc, options, yPos);

  // --- Full Width Deep Blue Line before Table ---
  doc.setDrawColor(DEEP_BLUE[0], DEEP_BLUE[1], DEEP_BLUE[2]);
  doc.setLineWidth(0.8);
  doc.line(0, yPos, pageWidth, yPos);

  yPos += 6; // Compact spacing

  drawTableSection(doc, options, yPos);

  return doc;
}

export function downloadPDF(doc: jsPDF, filename: string) {
  doc.save(filename);
}
