import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface CaseReportData {
  id: string;
  reportDate: string;
  diseaseCode: string;
  diseaseName: string;
  status: string;
  validationStatus: string;
  symptoms: string[];
  onsetDate: string;
  outcome?: string;
  facilityName: string;
  facilityCode?: string;
  patientInfo: string;
  patientNationalId?: string;
}

export interface ReportOptions {
  title: string;
  subtitle?: string;
  dateRange: { from: string; to: string };
  generatedAt: string;
  generatedBy: string;
  cases: CaseReportData[];
  filters?: {
    district?: string;
    facilityName?: string;
    diseaseCode?: string;
    status?: string;
    validationStatus?: string;
  };
}

const diseaseNames: Record<string, string> = {
  CHOLERA: "Cholera",
  MAL01: "Malaria",
  SARI: "Severe Acute Respiratory Illness",
  AFP: "Acute Flaccid Paralysis",
  YELLOW_FEVER: "Yellow Fever",
  RUBELLA: "Rubella",
  MEASLES: "Measles",
  PLAGUE: "Plague",
  RABIES: "Rabies",
  EBOLA: "Ebola Virus Disease",
  MONKEYPOX: "Monkeypox",
  TYPHOID: "Typhoid Fever",
  HEPATITIS_E: "Hepatitis E",
};

const getDiseaseName = (code: string): string => {
  return diseaseNames[code] || code;
};

function drawHeader(doc: jsPDF): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Logo placeholder (public folder)
  try {
    doc.addImage("/rbc_logo.png", "PNG", 14, 12, 40, 20);
  } catch {}

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(33, 37, 41);
  doc.text(
    "Rwanda National Integrated Disease Surveillance and Response",
    50,
    18,
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text("Ministry of Health | Republic of Rwanda", 50, 24);

  doc.setDrawColor(214, 217, 222);
  doc.line(14, 34, pageWidth - 14, 34);

  return 42;
}

function drawTitleSection(
  doc: jsPDF,
  options: ReportOptions,
  yPos: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(33, 37, 41);
  doc.text(options.title, pageWidth / 2, yPos, { align: "center" });

  yPos += 8;

  doc.setFontSize(9);

  const dateDetailsText = `Period: ${options.dateRange.from} to ${options.dateRange.to} - Generated: ${options.generatedAt}`;

  doc.text(
    dateDetailsText,
    pageWidth / 2, // Horizontal center
    yPos, // Vertical position
    { align: "center" },
  );

  return yPos + 12;
}

function drawTableSection(
  doc: jsPDF,
  options: ReportOptions,
  startY: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  const tableData = options.cases.map((c, index) => {
    const details: string[] = [];

    if (c.symptoms?.length) {
      details.push(
        `Symptoms: ${c.symptoms.slice(0, 3).join(", ")}${c.symptoms.length > 3 ? "..." : ""}`,
      );
    }

    if (c.outcome) {
      details.push(`Outcome: ${c.outcome}`);
    }

    const facilityDisplay = c.facilityCode
      ? `${c.facilityName} (${c.facilityCode})`
      : c.facilityName;

    return [
      index + 1,
      c.patientInfo,
      getDiseaseName(c.diseaseCode),
      facilityDisplay,
      c.status.toUpperCase(),
      c.validationStatus.toUpperCase(),
      c.reportDate,
      details.join("\n"),
    ];
  });

  autoTable(doc, {
    startY,

    head: [
      [
        "SN",
        "Patient",
        "Disease",
        "Facility",
        "Status",
        "Validation",
        "Report Date",
        "Clinical Notes",
      ],
    ],

    body: tableData,

    styles: {
      fontSize: 7,
      cellPadding: 2.8,
      overflow: "linebreak",
      lineColor: [214, 217, 222],
      lineWidth: 0.2,
      textColor: [33, 37, 41],
      valign: "middle",
    },

    headStyles: {
      fillColor: [35, 64, 142],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      halign: "center",
    },

    alternateRowStyles: {
      fillColor: [250, 251, 252],
    },

    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 30 },
      2: { cellWidth: 24 },
      3: { cellWidth: 30 },
      4: { cellWidth: 18, halign: "center" },
      5: { cellWidth: 20, halign: "center" },
      6: { cellWidth: 20, halign: "center" },
      7: { cellWidth: "auto" },
    },

    didParseCell: function (data) {
      if (
        data.section === "body" &&
        (data.column.index === 4 || data.column.index === 5)
      ) {
        data.cell.styles.fontStyle = "bold";
      }
    },

    didDrawPage: function (data) {
      const height = doc.internal.pageSize.getHeight();

      doc.setDrawColor(214, 217, 222);
      doc.line(14, height - 14, pageWidth - 14, height - 14);

      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);

      doc.text(`Generated by: ${options.generatedBy}`, 14, height - 8);

      doc.text(
        `${data.pageNumber}/${doc.getNumberOfPages()}`,
        pageWidth - 14,
        height - 8,
        { align: "right" },
      );
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY;
  return finalY;
}

export function generateCaseReportPDF(options: ReportOptions): jsPDF {
  const doc = new jsPDF();
  // TODO: use or remove
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = drawHeader(doc);
  yPos = drawTitleSection(doc, options, yPos);
  yPos = drawTableSection(doc, options, yPos);

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
  }

  return doc;
}

export function downloadPDF(doc: jsPDF, filename: string) {
  doc.save(filename);
}
